import './globals.css'
import { Poppins, Ubuntu } from 'next/font/google'


const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })
// const ubuntu = Ubuntu({subsets : ['latin'],  weight: ["300", "400",  "500",  "700", "300", "400", "500", "700"] })

export const metadata = {
  title: 'Currency Converter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
